### ISSUE TITLE
Adopt the wave module

### ISSUE THREAD

**Issue by cygkichi** [cygkichi/soundbrick#1]
# TODO
- [ ] Implement a function to select a wave module.
- [ ] Confirmation of the operation.
- [ ] Update the documentation.
